"""add_composite_indexes

Revision ID: c51f2b10ee49
Revises: i1ej6f7g8h9i
Create Date: 2026-04-13 22:24:51.499824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51f2b10ee49'
down_revision: Union[str, Sequence[str], None] = 'i1ej6f7g8h9i'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_logs_created_at', 'api_logs', ['created_at'], unique=False)
    op.create_index('ix_messages_conversation_id_sender', 'messages', ['conversation_id', 'sender'], unique=False)
    op.create_index('ix_settlements_merchant_id_settlement_date', 'settlements', ['merchant_id', 'settlement_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settlements_merchant_id_settlement_date', table_name='settlements')
    op.drop_index('ix_messages_conversation_id_sender', table_name='messages')
    op.drop_index('ix_api_logs_created_at', table_name='api_logs')
    # ### end Alembic commands ###
